# This file tells Netlify how to build and deploy your site.

[build]
  # This tells Netlify where your serverless function code is located.
  functions = "functions"

# This is a redirect rule that makes our function easier to call from the frontend.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
